Repository IllyShaieb/ACE, pull requests merged in 2022-03, with the labels that each got.

#1 Continuous integration setup
  .github/workflows/continuous_integration.yaml
  pyproject.toml
Labels: enhancement

#4 Readme badges
  README.md
Labels: documentation

#5 Deepsource setup
  .deepsource.toml
Labels: enhancement

#7 Add version to .deepsource.toml
  .deepsource.toml
Labels: bug

#13 Update link for the Codacy badge in README.md
  README.md
Labels: documentation

#14 Add match statement to the main function
  main.py
Labels: enhancement

#17 Refactor predict function
  ace/net.py
  main.py
  tests/test_ace.py
Labels: enhancement
